version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:7.0.5
    environment:
      - MONGO_DATABASE="quiz"
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
